name: one

on: [push]
jobs:
  make:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v1
    - name: Make
      run: make
    - name: upload
      uses: actions/upload-artifact@v1
      with:
        name: storage
        path: scheduler
  one:
    needs: make
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v1
    - name: Download scheduler
      uses: actions/download-artifact@v1
      with:
        name: storage
    - shell: bash
      run: |
        mv storage/scheduler .
        chmod u+x scheduler
    - name: Run
      run: ./scripts/test_singular.sh 1
  two:
    needs: make
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v1
    - name: Download scheduler
      uses: actions/download-artifact@v1
      with:
        name: storage
    - shell: bash
      run: |
        mv storage/scheduler .
        chmod u+x scheduler
    - name: Run
      run: ./scripts/test_singular.sh 2
  three:
    needs: make
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v1
    - name: Download scheduler
      uses: actions/download-artifact@v1
      with:
        name: storage
    - shell: bash
      run: |
        mv storage/scheduler .
        chmod u+x scheduler
    - name: Run
      run: ./scripts/test_singular.sh 3
  four:
    needs: make
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v1
    - name: Download scheduler
      uses: actions/download-artifact@v1
      with:
        name: storage
    - shell: bash
      run: |
        mv storage/scheduler .
        chmod u+x scheduler
    - name: Run
      run: ./scripts/test_singular.sh 4
  five:
    needs: make
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v1
    - name: Download scheduler
      uses: actions/download-artifact@v1
      with:
        name: storage
    - shell: bash
      run: |
        mv storage/scheduler .
        chmod u+x scheduler
    - name: Run
      run: ./scripts/test_singular.sh 5
  six:
    needs: make
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v1
    - name: Download scheduler
      uses: actions/download-artifact@v1
      with:
        name: storage
    - shell: bash
      run: |
        mv storage/scheduler .
        chmod u+x scheduler
    - name: Run
      run: ./scripts/test_singular.sh 6
  seven:
    needs: make
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v1
    - name: Download scheduler
      uses: actions/download-artifact@v1
      with:
        name: storage
    - shell: bash
      run: |
        mv storage/scheduler .
        chmod u+x scheduler
    - name: Run
      run: ./scripts/test_singular.sh 7
  eight:
    needs: make
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v1
    - name: Download scheduler
      uses: actions/download-artifact@v1
      with:
        name: storage
    - shell: bash
      run: |
        mv storage/scheduler .
        chmod u+x scheduler
    - name: Run
      run: ./scripts/test_singular.sh 8
  nine:
    needs: make
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v1
    - name: Download scheduler
      uses: actions/download-artifact@v1
      with:
        name: storage
    - shell: bash
      run: |
        mv storage/scheduler .
        chmod u+x scheduler
    - name: Run
      run: ./scripts/test_singular.sh 9
  ten:
    needs: make
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v1
    - name: Download scheduler
      uses: actions/download-artifact@v1
      with:
        name: storage
    - shell: bash
      run: |
        mv storage/scheduler .
        chmod u+x scheduler
    - name: Run
      run: ./scripts/test_singular.sh 10
  eleven:
    needs: make
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v1
    - name: Download scheduler
      uses: actions/download-artifact@v1
      with:
        name: storage
    - shell: bash
      run: |
        mv storage/scheduler .
        chmod u+x scheduler
    - name: Run
      run: ./scripts/test_singular.sh 11
  
  